<a href="https://colab.research.google.com/github/zolzayakh/Dive-into-coding/blob/main/Leveraging_Object_Orientation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

**[Problem 1] Enumeration of classes used so far**

Pandas: DataFrame

Matplotlib:Figure

Scikit-learn: 

Classifiers: LinearRegression, SVC, RandomForestRegressor
Preprocessing classes: OneHotEncoder, LabelEncoder, SimpleImputer


**[Problem 2] List of methods and instance variables that have been used so far**
*   Pandas: info(), concat()
*   Matplotlib: plot(), show()
*   Scikit-learn: fit(), fit_transform()

**[Problem 3] Create a standardized class by scratch**

In [6]:
import numpy as np
from sklearn.datasets import load_iris
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """

        self.mean_ = np.mean(X)
        self.var_ = np.var(X)

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特徴量
        """

        X_scaled =  - self.mean_
        X_scaled = X_scaled/self.var_

        pass
        return X_scaled

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
X_standard = scaler.transform(X)
print(X)
print(X_std)
print(X_standard)

平均 : 2.46
分散 : 3.1744
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
-0.7749495967741936
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


**[Problem 4] Creating a class that performs four arithmetic operations**

In [8]:
import warnings

class ArithmeticClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
        if not isinstance(value,  (int, float, complex)):
          warnings.warn("The value must be numeric!!!", DeprecationWarning)
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        if not isinstance(value2,  (int, float, complex)):
          warnings.warn("The value must be numeric!!!", DeprecationWarning)
        self.value += value2
    def sub(self, value2):
        """
        substraction
        """
        if not isinstance(value2,  (int, float, complex)):
          warnings.warn("The value must be numeric!!!", DeprecationWarning)
        self.value -= value2
    def mul(self, value2):
        """
        multiplication
        """
        if not isinstance(value2,  (int, float, complex)):
          warnings.warn("The value must be numeric!!!", DeprecationWarning)
        self.value *= value2
    def div(self, value2):
        """
        division
        """
        if not isinstance(value2,  (int, float, complex)) or value2 == 0:
          warnings.warn("The value must be numeric!!! or cannot divided by zero!", DeprecationWarning)
        if value2!=0:
          self.value /= value2

example = ArithmeticClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.mul(3)
print("value : {}".format(example.value))
example.div(2)
print("value : {}".format(example.value))
example.div(0)
print("value : {}".format(example.value))
#example.sub('three')
#print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 24
value : 12.0
value : 12.0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:48: DeprecationWarning: The value must be numeric!!! or cannot divided by zero!
