<a href="https://colab.research.google.com/github/zolzayakh/Dive-into-coding/blob/main/Matrix_production_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**[Problem 2] Calculation by NumPy function**

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [2]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

**[Problem 3] Implement the calculation of a certain element**

In [38]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

mul = [[0 for x in range(3)] for y in range(3)]
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray[0])):
        for k in range(len(b_ndarray)):
            mul[i][j] += a_ndarray[i][k] * b_ndarray[k][j]

for r in mul: 
  print(r)

[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


**[Problem 4] Creation of a function that performs matrix multiplication**

In [11]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def matrix(a, b):
  mul = [[0 for x in range(3)] for y in range(3)]
  for i in range(len(a_ndarray)):
      for j in range(len(b_ndarray[0])):
          for k in range(len(b_ndarray)):
             mul[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
  return(mul)
 
mat_mul = matrix(a_ndarray, b_ndarray)
for r in mat_mul:
  print(r)

[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


In [39]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def matrix(a, b):
  mul = [[0 for x in range(3)] for y in range(3)]
  for i in range(len(d_ndarray)):
      for j in range(len(e_ndarray[0])):
          for k in range(len(e_ndarray)):
             mul[i][j] += d_ndarray[i][k] * e_ndarray[k][j]
  return(mul)
 
mat_mul = matrix(d_ndarray, e_ndarray)
for r in mat_mul:
  print(r)



[21, -18, 1]
[-66, 57, 8]
[0, 0, 0]


**[Problem 5] Judging the input for which the calculation is not defined**

In [41]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def matri(a, b):
  if a.shape[0] == b.shape[1]:  
    mul = [[0 for x in range(3)] for y in range(3)]
    for i in range(len(d_ndarray)):
        for j in range(len(e_ndarray[0])):
            for k in range(len(e_ndarray)):
                mul[i][j] += d_ndarray[i][k] * e_ndarray[k][j]
    return(mul)
  else:
    return("Incorrect dimension!")

 
mat_mul1 = matri(d_ndarray, e_ndarray)
print(mat_mul1)

Incorrect dimension!


**【Question 6】Replacement**

In [49]:
import numpy as np
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]]).T
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
def matrix_trans(a, b):
  if a.shape[1] == b.shape[0]:  
    mul = [[0 for x in range(3)] for y in range(3)]
    for i in range(len(d_ndarray)):
        for j in range(len(e_ndarray[0])):
            for k in range(len(e_ndarray)):
                mul[i][j] += d_ndarray[i][k] * e_ndarray[k][j]
    return(mul)
  else:
    return("Incorrect dimension!")

mat_mul1 = matrix_trans(d_ndarray, e_ndarray)
print(mat_mul1)

[[33, -28, 9], [-48, 41, -6], [9, -6, 45]]


In [50]:
np.dot(d_ndarray, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])